### ISSUE TITLE
Include the support from Digitalisation Platform on the main login page 

### ISSUE THREAD

**Issue by harsha5500** [kthcloud/console#187]
**Is your feature request related to a problem? Please describe.**
We received some support for buying hardware from KTH Digitalisation platform. We need to include them for their support on the main page. 

**Describe the solution you'd like**
Please add a small but visible div with header for support. Link it to KTH Digitalization in Sv and En "https://www.kth.se/en/forskning/forskningsplattformar/digitalisering/start-1.861040"

**Describe alternatives you've considered**
Maybe add a "About" in the main console to see support and donations.

**Additional context**

![Screenshot 2024-02-06 at 11 31 55](https://github.com/kthcloud/console/assets/1305937/4c3406db-0186-4e52-9023-086873d5751c)
![Screenshot 2024-02-06 at 11 30 52](https://github.com/kthcloud/console/assets/1305937/a0f252ce-453e-4792-8330-5fe4525165f2)

**Comment by pierrelefevre** [comment]
Sure, I can add this :) There's already some info about it on the github organization readme and docs landing page. Do we have a complete list or who supported us?

**Comment by harsha5500** [comment]
Ah I saw that, "Our project is funded by KTH CBH and the Erasmus+ program of the European Union." You should add them too. This is to ensure everyone who helps gets publicity. :) One of costs of getting resources.
