### ISSUE TITLE
Resource limits when creating a VM

### ISSUE THREAD

**Issue by SimoneBendazzoli93** [kthcloud/console#199]
**Describe the bug**
When creating a VM from the console as an admin, the resource limits in the "Select specs" area seem to be wrongly indicated, or not having any effect in the final VM creation, since it is still possible to create a VM ignoring the red warnings about the resource limitation.
In the example below, I was still able to proceed and create a VM, despite the two errors.
**Screenshots**
![image](https://github.com/kthcloud/console/assets/25175838/66133aec-e49b-4e9f-a767-7928c4ce1764)

**Comment by pierrelefevre** [comment]
Thanks for reporting :) Yeah, being admin allows you to override the otherwise max quota for your account tier. I can remove the red warning for admins, since it doesn't do anything then
