### ISSUE TITLE
Link to MAIA registration page

### ISSUE THREAD

**Issue by SimoneBendazzoli93** [kthcloud/console#206]
Now we have a running MAIA Web Interface: [https://maia.cloud.cbh.kth.se](https://maia.cloud.cbh.kth.se). From there, users can request to register and get access to the MAIA resources. We are working on the users instructions on how to register in the MAIA system ( for now it's something super simple, only including e-mail and workspace name to be created, we are working on extending the options in the registration form also).

Can we add a link to this page in the KTHCloud console menu ?
![image](https://github.com/kthcloud/console/assets/25175838/5681e064-6ddf-4806-8c0a-108d0be0d5e2)

**Comment by pierrelefevre** [comment]
Sure thing :) Would you like to submit a PR?

You can branch off `beta`, which will appear on https://beta.app.cloud.cbh.kth.se/

**Comment by pierrelefevre** [comment]
You can find the menu component here:
 https://github.com/kthcloud/console/blob/main/src%2Flayouts%2Fdashboard%2FMenu.jsx

**Comment by SimoneBendazzoli93** [comment]
Ok, I will do that then!
