### ISSUE TITLE
"error" when creating a new vm

### ISSUE THREAD

**Issue by jconradt** [kthcloud/console#221]
Hello!

I have signed up with my KTH account "jconradt" to test the CBH cloud.
When creating a VM, I get the message "error" after some time. No other info visible to me.

I tried two machines at the different locations.

Is there anything else I need to configure / setup before starting the VM?

Thanks + greetings, Jörg

**Comment by pierrelefevre** [comment]
Hi Jörg! Thanks for the issue :)

We have some problems with VM creation currently, hoping to have a fix within a week or two. You can see the work progress in our `go-deploy` repo.

Deployments should work fine though, if your workload can be run in Docker.

**Comment by jconradt** [comment]
Hi Pierre, thanks for your super-fast response. I think I'll need a VM; so I'll wait a little longer.
Meanwhile, can you tell me how much memory the GPU cards in your cloud provide? Are they all RTX A6000 with 48GB each? Or does this differ between machines?
Greetings, Jörg

**Comment by pierrelefevre** [comment]
I think this is best answered in our Discord, if you'd like to continue the discussion there :) https://discord.gg/MuHQd6QEtM
