### ISSUE TITLE
Can't stop or start VMs

### ISSUE THREAD

**Issue by DorvoG** [kthcloud/console#236]
**Describe the bug**
When I try to stop or start a VM, I get an error message that says "unknown error" and nothing happens.

**To Reproduce**
1. Create VM
2. Click on stop or start or restart
3. ?????

**Expected behavior**
I expected the VM to stop so I could change settings.

**Screenshots**
![image](https://github.com/kthcloud/console/assets/132702317/4886ec68-b031-4f56-9e46-cc3f4e2551c0)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 124

**Comment by pierrelefevre** [comment]
Hey! Thanks for the bug report and sorry you're experiencing issues. Are you using the beta page?
