### ISSUE TITLE
Make secrets a bit more secret in the CLI box

### ISSUE THREAD

**Issue by saffronjam** [kthcloud/console#244]
Right now we hide the Docker secrets in the GitHub actions box. However, the Docker CLI commands (Right above) still has the secrets visible.

Maybe the button can copy the commands with the secrets, and then hide them in the GUI?

![image](https://github.com/kthcloud/console/assets/26722370/7e9e2096-9fe0-4839-aed1-912b0d5ff581)

**Comment by pierrelefevre** [comment]
that's a nice deployment you got there

**Comment by pierrelefevre** [comment]
Thanks for pointing this out, would be easy for some secrets to slip into a screenshot. Imagine what someone could do to that deployment

**Comment by pierrelefevre** [comment]
like IMAGINE https://test-deployment.app.cloud.cbh.kth.se/

**Comment by saffronjam** [comment]
I just wanted to show you the DANGER of showing secrets
