### ISSUE TITLE
Allow deployment restarts in more scenarios, or all?

### ISSUE THREAD

**Issue by saffronjam** [kthcloud/console#250]
Restarts of deployments should probably never be restricted in the frontend. 

For example, the new MountFailed error is resolved by the user creating the folder in the storage and then restart the deployment. However, when a resource is not running I can't restart the deployment.

Sure the user can wait for the repair job to kick in and create the folder automatically, but those might only run like every 30 minutes.

![image](https://github.com/kthcloud/console/assets/26722370/835fcc28-cb7f-4165-b7ad-f8541cbb8ee3)

**Comment by pierrelefevre** [comment]
https://media.tenor.com/uS1s5Vi1ycoAAAAi/the-sims-the-sims4.gif mount failed

**Comment by saffronjam** [comment]
Gosh damnit, my mountain broke!
