### ISSUE TITLE
Increase size of Gravatar images

### ISSUE THREAD

**Issue by saffronjam** [kthcloud/console#256]
This is blurry as hell! We should probably increase the size

![image](https://github.com/kthcloud/console/assets/26722370/8911ae60-867d-46e1-9421-5df5008d7138)

Increase the size by adding the ?s param to the URL depending on the location in the console

<img src="https://www.gravatar.com/avatar/064ce0f451ab013aec0c8b011c2754837100af0e270e78acae73749cdb7e75fb?s=10"/>
<img src="https://www.gravatar.com/avatar/064ce0f451ab013aec0c8b011c2754837100af0e270e78acae73749cdb7e75fb?s=20"/>
<img src="https://www.gravatar.com/avatar/064ce0f451ab013aec0c8b011c2754837100af0e270e78acae73749cdb7e75fb?s=40"/>
<img src="https://www.gravatar.com/avatar/064ce0f451ab013aec0c8b011c2754837100af0e270e78acae73749cdb7e75fb?s=80"/>
<img src="https://www.gravatar.com/avatar/064ce0f451ab013aec0c8b011c2754837100af0e270e78acae73749cdb7e75fb?s=160"/>
<img src="https://www.gravatar.com/avatar/064ce0f451ab013aec0c8b011c2754837100af0e270e78acae73749cdb7e75fb?s=320"/>

**Comment by pierrelefevre** [comment]
![Uploading image.png…]()

**Comment by pierrelefevre** [comment]
![Uploading image.png…]()

**Comment by pierrelefevre** [comment]
![image](https://github.com/kthcloud/console/assets/35996839/44650c6d-0d17-4787-b85e-2fd3c08e721b)

**Comment by pierrelefevre** [comment]
![image](https://github.com/kthcloud/console/assets/35996839/56cbf8a5-9f7f-4bdf-968b-8d1627b51908)
damn now he lookin GOOOOD
