### ISSUE TITLE
Can´t access deployments 

### ISSUE THREAD

**Issue by Phillezi** [kthcloud/console#264]
**Cant access deployments**
When i click any deployment i get a white screen.
Started happening today, worked an hour ago.

**To Reproduce**
1. Go to [deploy](https://cloud.cbh.kth.se/deploy)
2. Click on any deployment
4. See white screen and check console: 
I get this:
![image](https://github.com/kthcloud/console/assets/112874974/ea1f1680-5d5b-40be-b454-3367c6d9b53a)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Chrome
 - Version 124.0.6367.155 (Official Build) (64-bit)

**Comment by Phillezi** [comment]
I can access my deployments on the beta

**Comment by pierrelefevre** [comment]
Hmm, might be related to some updates in the API. Could you try hard reloading the frontend quickly?

**Comment by pierrelefevre** [comment]
![image](https://github.com/kthcloud/console/assets/35996839/faf78a35-5d4d-4c9c-8f35-96ce4aeef87f)

**Comment by pierrelefevre** [comment]
(Empty cache and hard reload)

**Comment by Phillezi** [comment]
Its the same after Empty cache and hard reload

**Comment by pierrelefevre** [comment]
Interesting, then it's definitely the API changes! Thanks :)
Will merge now so the update should rollout in a few minutes

**Comment by Phillezi** [comment]
Works now :+1:
