### ISSUE TITLE
Show replica status

### ISSUE THREAD

**Issue by pierrelefevre** [kthcloud/console#272]
For deployments with multiple replicas, it is difficult to grok the overall health of all replicas with only one status indicator. Therefore, we now expose the number of replicas for each status. A component showing this is needed, which could perhaps live by the top bar, like in the following crude photoshop mockup (less wide would look nicer).
![Screenshot from 2024-05-15 23-09-30](https://github.com/kthcloud/console/assets/35996839/340502a4-e02f-4cfe-8e69-1dfd6e7b5f22)

Inspiration: Rancher replica status overview 
> overview
>![image](https://github.com/kthcloud/console/assets/35996839/2b658b8f-be8f-457b-8492-49d8b2ce8d71)

> expanded
>![image](https://github.com/kthcloud/console/assets/35996839/1cb46aa6-0dfa-4e9a-b5f2-2f78b75576a4)

Looks like this in the deployment object
```json
  "replicaStatus": {
    "desiredReplicas": 1,
    "readyReplicas": 1,
    "availableReplicas": 1,
    "unavailableReplicas": 0
  }
```

Some conditions:
- Only show for deployments
- Only show when replicas > 1
- Dropdown listing the status (Add i18n locale labels for each status)

**Comment by Phillezi** [comment]
Hi!

I started to work on this but i have a few questions,
what statuses are wanted, and what should they represent.

I currently have these:
* **Ready**: Amount gotten from `readyReplicas` for replicas that are ready, no current action (showed in green)
* **Occupied**: Amount gotten from `availableReplicas - readyReplicas` for replicas that are doing something (showed in blue) **does this make sense?**
* **Unavailable**: Amount gotten from `unavailable replicas` for replicas that are unavailable.

(The colors are temporary, just using "green", "blue" and "red")

![image](https://github.com/kthcloud/console/assets/112874974/c3331c8f-8cc9-42f9-a8c1-4e0c649c573e)

**Comment by pierrelefevre** [comment]
Adding @saffronjam to the loop, what do you think makes most sense, not sure what the difference between ready and available is here

**Comment by saffronjam** [comment]
Statuses are taken directly from Kubernetes. Here's a post describing them :) https://stackoverflow.com/questions/66317251/couldnt-understand-availablereplicas-readyreplicas-unavailablereplicas-in-dep

**Comment by pierrelefevre** [comment]
> Hi!
> 
> I started to work on this but i have a few questions, what statuses are wanted, and what should they represent.
> 
> I currently have these:
> 
> * **Ready**: Amount gotten from `readyReplicas` for replicas that are ready, no current action (showed in green)
> * **Occupied**: Amount gotten from `availableReplicas - readyReplicas` for replicas that are doing something (showed in blue) **does this make sense?** _Edit: busy might be a better name for this_
> * **Unavailable**: Amount gotten from `unavailableReplicas` for replicas that are unavailable.
> * **Wanted**: Amount gotten from `desiredReplicas - (availableReplicas + unavailableReplicas)` for replicas that the user wants but doesnt exist.
> 
> ![image](https://private-user-images.githubusercontent.com/112874974/331840924-ce269eaa-7b9a-460f-948f-1f4e9c4f7ce7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxOTE5NTAsIm5iZiI6MTcxNjE5MTY1MCwicGF0aCI6Ii8xMTI4NzQ5NzQvMzMxODQwOTI0LWNlMjY5ZWFhLTdiOWEtNDYwZi05NDhmLTFmNGU5YzRmN2NlNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMFQwNzU0MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNzhhNDYwODljNDNmYmNlYjQ0Mzk1ZmFhYzQxNDRmNmEzMGNjOWE2NjIyZmExZjA4YjAzNjViMzA4YTcwMjQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1MdnCnba3inrOtKFuX1ij9y_kmVqSuBMAdP2snmA7BI) ![image](https://private-user-images.githubusercontent.com/112874974/331867290-64e252c6-671b-4bd5-9b8f-92c283dc6933.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxOTE5NTAsIm5iZiI6MTcxNjE5MTY1MCwicGF0aCI6Ii8xMTI4NzQ5NzQvMzMxODY3MjkwLTY0ZTI1MmM2LTY3MWItNGJkNS05YjhmLTkyYzI4M2RjNjkzMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMFQwNzU0MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZjExODgwZDQyZmI3MjcyZWQyNWE5ZTk0M2RlMjBlMDc1ZDVmNTc1MzVkOWUzMDljOGNlOGYyOTMzZGU2YmUyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WNBbiMYduDTeCcTTRInuxSYjtOHwQcST5h4_v9rzn3Y)

Nice updated mockup! I think this makes sense, maybe we could use Desired instead of Wanted since that seems to be the wording used in many K8s docs, but other than that it looks great :)

**Comment by Phillezi** [comment]
Thanks!

Yes, desired may be better, I just wanted to differantiate between desired at first since it is displaying the amount of:
`desiredReplicas - (availableReplicas + unavailableReplicas)`.

Will take a look at the k8s replicaSet status docs to make sure they match.

**Comment by Phillezi** [comment]
Hi again,

I can´t get the status to show for multiple replicas, i created a deployment to test without hard-coded values and i get the same replicaStatus regardess of the number of replicas on the deployment.

```json
{
        "id": "0fc7e863-8cb5-4ecd-b49c-ad8f8de673f5",
        "name": "joyfully-cautiously-minus",
        "type": "prebuilt",
        "ownerId": "4efea96b-2d6b-41f6-96a2-656f18d6f8d1",
        "zone": "se-flem-2",
        "createdAt": "2024-05-20T18:30:57.963Z",
        "updatedAt": "2024-05-20T18:35:39.328Z",
        "accessedAt": "2024-05-20T18:35:52.479Z",
        "cpuCores": 0.2,
        "ram": 0.5,
        "replicas": 4,
        "url": "https://joyfully-cautiously-minus.app.cloud.cbh.kth.se",
        "envs": [
            {
                "name": "NAME",
                "value": "THIS_IS_A_DUMMY"
            },
            {
                "name": "PORT",
                "value": "8080"
            }
        ],
        "volumes": [],
        "initCommands": [],
        "args": [],
        "private": false,
        "internalPort": 8080,
        "image": "nginx:latest",
        "healthCheckPath": "/healthz",
        "status": "resourceRunning",
        "replicaStatus": {
            "desiredReplicas": 1,
            "readyReplicas": 1,
            "availableReplicas": 1,
            "unavailableReplicas": 0
        },
        "pingResult": 502,
        "integrations": [],
        "teams": [],
        "storageUrl": "..."
    },

```

**Comment by saffronjam** [comment]
That's because we are "cheating" a little bit. Having more replicas just edits your scaler (HPA) so that you could have more given your load. So if you add more load, like http requests, more pods will probably be created.

A tool like siege is useful! ☺️
