### ISSUE TITLE
Add whiteSpace nowrap to x-scrollable tables

### ISSUE THREAD

**Issue by pierrelefevre** [kthcloud/console#298]
![Screenshot_20240601-233451.png](https://github.com/kthcloud/console/assets/35996839/fc3e70ef-82d6-4bc3-b5ec-8d15273e40b6)

Doesn't make sense for the text to wrap on mobile and make everything super weird and ugly since the entire table container is x-scrollable as per material ui guidelines

**Comment by Phillezi** [comment]
I created a tiny component `NoWrapTable.tsx` that just wraps Table with whiteSpace: "nowrap" in `components`:
```javascript
import { Table, styled } from "@mui/material";

const NoWrapTable = styled(Table)({
  whiteSpace: "nowrap",
});

export default NoWrapTable;
```
Here's how it looks on the GPU types table
![image](https://github.com/kthcloud/console/assets/112874974/c1811950-8faa-405e-a6fb-1f4631e731eb)

Should nowrap be used on all tables? 
![image](https://github.com/kthcloud/console/assets/112874974/e57dc97e-08fb-4040-9684-c5755a42035e)

**Comment by Phillezi** [comment]
StorageManager.tsx might be better off with text wrapping,
With long storage paths is seems tedious to scroll, or what do you think is best?
![image](https://github.com/kthcloud/console/assets/112874974/5315564d-73f5-4e51-befd-e5c92aab12ef)
![image](https://github.com/kthcloud/console/assets/112874974/f62f6118-ea6b-4578-835d-fa8c924098b2)
