### ISSUE TITLE
Feature request: Init commands

### ISSUE THREAD

**Issue by Phillezi** [kthcloud/console#302]
**Is your feature request related to a problem? Please describe.**
It would be nice to be able to set init commands using the console, if you for example want to use keycloak with the start command.

**Describe the solution you'd like**
A text field similar to the one in the ImageManager would be nice, that on save updates the initCommands field on the deployment.

**Describe alternatives you've considered**
It could work like the EnvManager otherwise, where the user can insert each command manually and it being displayed as a Table.

**It could look something like this**
![image](https://github.com/kthcloud/console/assets/112874974/2289a0dc-4b75-4c07-af9b-fb335329c8bf)

**Comment by Phillezi** [comment]
I have made a component for this: `InitCommandManager.tsx` it is pretty similar to `ImageManager.tsx` but it splits the commands by space into a string array and warns the user if they exceed 100 commands (100 was specified as max in the go-deploy model).

I'm just unsure if splitting by space is correct, 
should `mongod --auth` be treated as one command or as two commands?
If i split by space the it becomes
```json
...
"initCommands": [
  "mongod",
  "--auth"
] 
```
Here's how it looks:
![image](https://github.com/kthcloud/console/assets/112874974/0ae0f91f-c5db-40ab-8312-ad012f1086f1)
![image](https://github.com/kthcloud/console/assets/112874974/17aac09f-314e-4d52-96f6-fa5231f2523d)

The text should probably be changed to be more descriptive, let me know what you think.

Also let me know if you think if it is better to handle it like the EnvManager does with environment variables (in a table)

**Comment by pierrelefevre** [comment]
I believe this is a duplicate of https://github.com/kthcloud/console/issues/198?

**Comment by Phillezi** [comment]
oh yeah, sorry

**Comment by pierrelefevre** [comment]
The current version is pretty bare bones however so feel free to refine it :D

**Comment by pierrelefevre** [comment]
I'll merge it to main so you can check it out on a local branch
