### ISSUE TITLE
`Create A VM first` button in GPU manager page is "off-center"

### ISSUE THREAD

**Issue by saffronjam** [kthcloud/console#313]
![image](https://github.com/kthcloud/console/assets/26722370/9d19bff9-77fc-4871-809d-036ac7c44cd1)

**Comment by pierrelefevre** [comment]
Do you mean the C and A are not aligned? The button border seems aligned with the table column?

**Comment by saffronjam** [comment]
This was the screenshot I wanted to post! 

![image](https://github.com/kthcloud/console/assets/26722370/b4f21b03-244f-490c-9c9b-d53f9044e538)

It looks a bit strange since it does not look like a button until its hovered

**Comment by pierrelefevre** [comment]
Ah I see, we should probably right align (flexEnd) the stack with gap, I think 3 is usually used
