### ISSUE TITLE
Support new deployment deployment visibility modes 

### ISSUE THREAD

**Issue by pierrelefevre** [kthcloud/console#322]
go-deploy has added new visibility modes for deployments instead of just public and private. 

We could make some sort of slider instead of the existing toggle switch

```
--[x]---------[ ]-----------------[ ]------------[ ]---
Public  Private (teams)   Private (only you)    Hidden

<-- More public -- More private -->
```

**Comment by Phillezi** [comment]
How about using a [`ToggleButtonGroup`](https://mui.com/material-ui/react-toggle-button/#exclusive-selection) with togglebuttons inside? Quick mockup:
![image](https://github.com/kthcloud/console/assets/112874974/55379a2f-4549-4473-8e8e-7f3063793543)

**Comment by pierrelefevre** [comment]
Sounds good!

**Comment by Phillezi** [comment]
Quick question, how is hidden set?

In the struct from go-deploy
```go
...
Visibility string `json:"visibility" bson:"visibility" binding:"omitempty,oneof=public private auth"`
...
```
which gives these possible values
```TypeScript
type visibility = "public" | "private" | "auth" | undefined;

```
right?

**This is my current interpretation, please let me know if I have misunderstood anything:**
Public                        -->    public
Private (Teams)       -->    private
Private (Only You)   -->    auth ["When auth, deploy a oauth proxy which only allows the deployment owner."](https://github.com/kthcloud/go-deploy/issues/647#issue-2333083870)
Hidden                      -->    ?

**Comment by pierrelefevre** [comment]
Might be a mistake when writing the issue!

**Comment by Phillezi** [comment]
This issue or #647?
